### ISSUE TITLE
captureClicks captures anchor link clicks

### ISSUE THREAD

**Issue by mz3** [cyclejs/history#27]
``` html
<a href='#myAnchor'>...</a>
```

Expected behaviour: page jumps to anchor element
Actual behaviour: router re-runs current component/app

I can submit a PR if wanted. I think it's just a matter of changing

captureClicks.js:42

``` js
if (link && link.indexOf('mailto:') > -1 || link === '#') {
    return;
}
```

to

``` js
if (link && link.indexOf('mailto:') > -1 || link.charAt(0) === '#') {
    return;
}
```

~~Something extra may be needed though to scroll down to the appropriate element after render if a hash link is visited directly/typed into address bar (i.e. http://localhost:3000/#myAnchor).~~

**Comment by TylorS** [comment]
Ahh yes, PR welcomed.

**Comment by staltz** [comment]
By the way, I'm in the process of migrating this repo to the monorepo.

**Comment by TylorS** [comment]
@staltz I'd go ahead and move to the monorepo, we can sort everything else out after.

**Comment by staltz** [comment]
This is now moved to the monorepo.

**Comment by staltz** [comment]
The PR there would be welcomed. :)
